rm(list = ls(all=TRUE))
library(ggfortify)
library(ggplot2)
library(ggpubr)
library(ggbiplot)
library(phytools)
library(nlme)
library(geiger)
library(ggtree)
library(stringr)
library(dplyr)
library(RSQLite)
df_long = read.csv('BIO_Life_History.csv', header = TRUE, sep = ';')
